# Generated by Django 5.2.7 on 2025-12-01 00:09

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),  # make sure this matches your last migration
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_technician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(max_length=50, choices=[
                ('', 'Select a specialty'),
                ('nail_technician', 'Nail Technician'),
                ('esthetician', 'Esthetician'),
                ('makeup_artist', 'Makeup Artist'),
                ('loctician', 'Loctician'),
                ('barber', 'Barber'),
                ('braider', 'Braider'),
                ('hairstylist', 'Hairstylist'),
                ('massage_artist', 'Massage Artist'),
            ], blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='licensed',
            field=models.BooleanField(default=False),
        ),
    ]
