# Generated by Django 5.2.9 on 2025-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
