# Generated by Django 5.2.9 on 2025-12-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='background_color',
        ),
    ]
