# Generated by Django 5.2.8 on 2025-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='licenced',
            new_name='licensed',
        ),
        migrations.AlterField(
            model_name='technician',
            name='specialty',
            field=models.CharField(choices=[('', 'Select a specialty'), ('nail_technician', 'Nail Technician'), ('esthetician', 'Esthetician'), ('makeup_artist', 'Makeup Artist'), ('loctician', 'Loctician'), ('barber', 'Barber'), ('braider', 'Braider'), ('hairstylist', 'Hairstylist'), ('massage_artist', 'Massage Artist')], default='', max_length=50),
        ),
    ]
