# Generated by Django 5.2.7 on 2025-10-14 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('media_feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('video_upload', 'Video Uploaded'), ('photo_upload', 'Photo Uploaded'), ('video_liked', 'Video Liked'), ('photo_liked', 'Photo Liked'), ('comment_added', 'Comment Added'), ('appointment_booked', 'Appointment Booked'), ('appointment_reminder', 'Appointment Reminder'), ('follow', 'New Follower')], max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('related_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_feed.photo')),
                ('related_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_feed.video')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
